---
swagger: '2.0'
info:
  title: API V1
  version: v1
paths:
  "/api/v1/appointments":
    get:
      summary: list appointments
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
    post:
      summary: create appointment
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: appointment
        in: body
        schema:
          type: object
          properties:
            date_of_appointment:
              type: string
            time_of_appointment:
              type: string
            message:
              type: string
            user_id:
              type: string
            doctor_id:
              type: string
          required:
          - date_of_appointment
          - time_of_appointment
          - message
          - user_id
          - doctor_id
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/appointments/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show appointment
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
    delete:
      summary: delete appointment
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/doctors":
    get:
      summary: list doctors
      responses:
        '200':
          description: successful
    post:
      summary: create doctor
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      - name: doctor
        in: body
        schema:
          type: object
          properties:
            user_id:
              type: integer
            name:
              type: string
            photo:
              type: string
            specialty:
              type: string
            bio:
              type: string
          required:
          - user_id
          - name
          - photo
          - specialty
          - bio
      consumes:
      - application/json
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/doctors/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show doctor
      responses:
        '200':
          description: successful
    delete:
      summary: delete doctor
      parameters:
      - in: header
        type: string
        name: Authorization
        required: true
        description: Client token
      security:
      - Authorization: {}
      responses:
        '200':
          description: successful
  "/api/v1/users":
    get:
      summary: list users
      responses:
        '200':
          description: successful
    post:
      summary: create user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            role:
              type: string
            birth_date:
              type: string
            gender:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - birth_date
          - gender
          - password
          - password_confirmation,
          - role
      responses:
        '200':
          description: successful
  "/api/v1/users/{id}":
    parameters:
    - name: id
      in: path
      type: string
      description: id
      required: true
    get:
      summary: show user
      responses:
        '200':
          description: successful
    patch:
      summary: update user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            role:
              type: string
            birth_date:
              type: string
            gender:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - birth_date
          - gender
          - password
          - password_confirmation,
          - role
      responses:
        '200':
          description: successful
    put:
      summary: update user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            name:
              type: string
            email:
              type: string
            role:
              type: string
            birth_date:
              type: string
            gender:
              type: string
            password:
              type: string
            password_confirmation:
              type: string
          required:
          - name
          - email
          - birth_date
          - gender
          - password
          - password_confirmation,
          - role
      responses:
        '200':
          description: successful
    delete:
      summary: delete user
      responses:
        '200':
          description: successful
  "/login":
    post:
      summary: login user
      consumes:
      - application/json
      parameters:
      - name: user
        in: body
        schema:
          type: object
          properties:
            email:
              type: string
            password:
              type: string
          required:
          - email
          - password
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: 127.0.0.1:3000
